/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 Punto 1. ¿Cúal es este error o errores?
 -El error constaba en que el shift estaba invertido, y nos movía el dato pinNumber veces, cuando en realidad lo necesitamos
 en el bit 0, para que nos diera un 1 o 0 (dado que es el unico bit que lo permite). Además de que faltaba otra
 operación en el código para hacerlo leer el bit 0.
¿Cómo se pueden solucionar?
-Se cambió el sentido de los shitfs y ahora si arroja la informacion en el bit 0; luego agregamos una máscara (0b01) con un
AND (&), para extraer ese 1 o 0 lógico y verificar que el pin está recibiendo información o no.
 */


#include <stdint.h>
#include "stm32f4xx_hal.h"
#include "stm32_assert.h"
#include "gpio_driver_hal.h"

// Headers definition
int add (int x, int y);

// Definimos un pin de prueba
GPIO_Handler_t userLed = {0}; //	PinA5

/*
 * The main function, where everything happens.
 */
int main(void)
{
	/* Configuramos el pin */
	userLed.pGPIOx 							= 	GPIOA;
	userLed.pinConfig.GPIO_PinNumber		=	PIN_5;
	userLed.pinConfig.GPIO_PinMode			=	GPIO_MODE_OUT;
	userLed.pinConfig.GPIO_PinOutputType	=	GPIO_OTYPE_PUSHPULL;
	userLed.pinConfig.GPIO_PinOutputSpeed	=	GPIO_OSPEED_MEDIUM;
	userLed.pinConfig.GPIO_PinPuPdControl	=	GPIO_PUPDR_NOTHING;

		/* Cargamos la configuracion de los registros que configuran el puerto */
		gpio_Config(&userLed);

		gpio_WritePin(&userLed, SET);
		gpio_WritePin(&userLed, RESET);
		gpio_ReadPin (&userLed);
		gpio_TooglePin(&userLed);
	/* Loop forever */
	while(1){
		gpio_TooglePin(&userLed);
	}
}

/*
 * Esta funcion sirve para detectar problemas de parametros
 * incorrectos al momento de ejecutar el programa.
 * */
void assert_failed(uint8_t * file, uint32_t line){
	while(1){
		//problems...
	}
}







